### ISSUE TITLE
Criar tela de cadastro

### ISSUE THREAD

**Issue by damarcones** [Hackathon-FGA-2020/Desafio-1-Grupo-1#2]
**Requisitos:**
- [ ] Campo de e-mail;
- [ ] Campo de senha e confirmar senha;
- [ ] Validação do cadastro.

**Critérios de aceitação:**
- [ ] Finalizar os requisitos acima.

**Comment by brunaalmeidasantos** [comment]
Por problemas de conflito, a issue não pôde ser concluída
